### ISSUE TITLE
404 errors when running local dev instance

### ISSUE THREAD

**Issue by natea** [Stanford-Online/class2go#2047]
I've got a local instance running and successfully populated the database with ```./manage.py db_populate```, but when I click on the link to view the "Introduction to Databases" course, I get a 404 error:

http://localhost:8000/db/Winter2013 

Similarly, when I click on the "Solar Cells, Fuel Cells & Batteries" link, I get a 404 error:
http://localhost:8000/solar/Fall2012

But when I click on the "Introduction to Computer Science" link, it takes me to a page "Natural Language Processing"
http://localhost:8000/networking/Fall2012/preview/

**Comment by natea** [comment]
wow, are you guys resurrecting Class2Go?

On Friday, December 18, 2015, Steven Burch <notifications@github.com> wrote:

> Closed #2047 <https://github.com/Stanford-Online/class2go/issues/2047>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stanford-Online/class2go/issues/2047#event-496300259>.
>


-- 


Website: http://www.appsembler.com
Blog: http://www.appsembler.com/blog
Twitter: http://twitter.com/natea
LinkedIn: http://linkedin.com/in/natea
Phone: +1 (617) 702-4331

**Comment by stvstnfrd** [comment]
@natea Nope, just clearing out old tickets..
